"""empty message

Revision ID: a7a930c2da68
Revises: 16db72b9d379
Create Date: 2020-03-04 17:59:28.029666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7a930c2da68'
down_revision = '16db72b9d379'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('remember', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'remember')
    # ### end Alembic commands ###
